/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package explorer;

import java.io.File;
import javax.swing.JButton;

/**
 *
 * @author jawad
 */
public class Frontend extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private final Middleware MW = new Middleware();

    public Frontend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MusicJButton = new javax.swing.JButton();
        PicturesJButton = new javax.swing.JButton();
        DocumentJButton = new javax.swing.JButton();
        DownloadJButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        DisplayPanel = new javax.swing.JPanel();
        BackPanel = new javax.swing.JScrollPane();
        DesktopJButton = new javax.swing.JButton();
        ThisPCJButton = new javax.swing.JButton();
        VideosJButton = new javax.swing.JButton();
        URLTextField = new javax.swing.JTextField();
        ViewJButton = new javax.swing.JButton();
        RenameJButton = new javax.swing.JButton();
        DeleteJButton = new javax.swing.JButton();
        PasteJButton = new javax.swing.JButton();
        CopyJButton = new javax.swing.JButton();
        NewJButton = new javax.swing.JButton();
        BackjButton = new javax.swing.JButton();
        MovejButton = new javax.swing.JButton();
        SearchjButton = new javax.swing.JButton();
        BackJButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1307, 800));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FILE EXPLORER.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 40));

        MusicJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 14.png"))); // NOI18N
        MusicJButton.setMnemonic('6');
        MusicJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MusicJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 160, 30));

        PicturesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 10.png"))); // NOI18N
        PicturesJButton.setMnemonic('5');
        PicturesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PicturesJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PicturesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 30));

        DocumentJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 9.png"))); // NOI18N
        DocumentJButton.setMnemonic('4');
        DocumentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DocumentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, 30));

        DownloadJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 8.png"))); // NOI18N
        DownloadJButton.setMnemonic('3');
        DownloadJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DownloadJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 30));

        SearchTextField.setBackground(new java.awt.Color(153, 153, 0));
        SearchTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(SearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 180, 40));

        DisplayPanel.setBackground(new java.awt.Color(0, 102, 102));
        DisplayPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 10.png")))); // NOI18N
        DisplayPanel.add(BackPanel);

        getContentPane().add(DisplayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 1000, 450));

        DesktopJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 7.png"))); // NOI18N
        DesktopJButton.setMnemonic('2');
        DesktopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesktopJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DesktopJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 30));

        ThisPCJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 6.png"))); // NOI18N
        ThisPCJButton.setMnemonic('1');
        ThisPCJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThisPCJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ThisPCJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        VideosJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 12.png"))); // NOI18N
        VideosJButton.setMnemonic('7');
        VideosJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideosJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(VideosJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 160, 30));

        URLTextField.setEditable(false);
        URLTextField.setBackground(new java.awt.Color(153, 153, 0));
        URLTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(URLTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 112, 1000, 30));

        ViewJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 15.png"))); // NOI18N
        ViewJButton.setMnemonic('M');
        ViewJButton.setToolTipText("View");
        ViewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 61, 45));

        RenameJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 4.png"))); // NOI18N
        RenameJButton.setMnemonic('R');
        RenameJButton.setToolTipText("Rename");
        RenameJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenameJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RenameJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 61, 45));

        DeleteJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 3.png"))); // NOI18N
        DeleteJButton.setMnemonic('D');
        DeleteJButton.setToolTipText("Delete");
        DeleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 61, 45));

        PasteJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 2.png"))); // NOI18N
        PasteJButton.setMnemonic('V');
        PasteJButton.setToolTipText("Paste");
        PasteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PasteJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 61, 45));

        CopyJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 1.png"))); // NOI18N
        CopyJButton.setMnemonic('C');
        CopyJButton.setToolTipText("Copy");
        CopyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CopyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 61, 45));

        NewJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 5.png"))); // NOI18N
        NewJButton.setMnemonic('N');
        NewJButton.setToolTipText("New");
        NewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 61, 45));

        BackjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 18.png"))); // NOI18N
        BackjButton.setMnemonic('B');
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 95, 39));

        MovejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group 17.png"))); // NOI18N
        MovejButton.setMnemonic('X');
        MovejButton.setToolTipText("Move");
        MovejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovejButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MovejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 61, 45));

        SearchjButton.setBackground(new java.awt.Color(0, 0, 0));
        SearchjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vector.png"))); // NOI18N
        SearchjButton.setMnemonic('S');
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 40, 40));

        BackJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/triangle.png"))); // NOI18N
        getContentPane().add(BackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1307, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusicJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicJButtonActionPerformed
        // TODO add your handling code here:
        MW.music();
        URLTextField.setText("Music");
    }//GEN-LAST:event_MusicJButtonActionPerformed

    private void PicturesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PicturesJButtonActionPerformed
        // TODO add your handling code here:
        MW.picture();
        URLTextField.setText("Pictures");
    }//GEN-LAST:event_PicturesJButtonActionPerformed

    private void DocumentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentJButtonActionPerformed
        // TODO add your handling code here:
        MW.document();
        URLTextField.setText("Documents");
    }//GEN-LAST:event_DocumentJButtonActionPerformed

    private void DownloadJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadJButtonActionPerformed
        // TODO add your handling code here:
        MW.download();
        URLTextField.setText("Downloads");
    }//GEN-LAST:event_DownloadJButtonActionPerformed

    private void DesktopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesktopJButtonActionPerformed
        // TODO add your handling code here:
        MW.desktop();
        URLTextField.setText("Desktop");
    }//GEN-LAST:event_DesktopJButtonActionPerformed

    private void ThisPCJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThisPCJButtonActionPerformed
        // TODO add your handling code here:
        MW.pc();
    }//GEN-LAST:event_ThisPCJButtonActionPerformed

    private void VideosJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideosJButtonActionPerformed
        // TODO add your handling code here:
        MW.video();
        URLTextField.setText("Videos");
    }//GEN-LAST:event_VideosJButtonActionPerformed

    private void DeleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJButtonActionPerformed
        // TODO add your handling code here:
        MW.deleteMW();
    }//GEN-LAST:event_DeleteJButtonActionPerformed

    private void CopyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyJButtonActionPerformed
        // TODO add your handling code here:
        MW.copyMW();
    }//GEN-LAST:event_CopyJButtonActionPerformed

    private void PasteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteJButtonActionPerformed
        // TODO add your handling code here:
        MW.pasteMW();
    }//GEN-LAST:event_PasteJButtonActionPerformed

    private void RenameJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenameJButtonActionPerformed
        // TODO add your handling code here:
        MW.renameMW();
    }//GEN-LAST:event_RenameJButtonActionPerformed

    private void NewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewJButtonActionPerformed
        // TODO add your handling code here:
        MW.newMW();
    }//GEN-LAST:event_NewJButtonActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        // TODO add your handling code here:
        MW.backMW();
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void MovejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovejButtonActionPerformed
        // TODO add your handling code here:
        MW.moveMW();
    }//GEN-LAST:event_MovejButtonActionPerformed

    private void ViewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewJButtonActionPerformed

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        // TODO add your handling code here:
        MW.searchMW(URLTextField.getText(), SearchTextField.getText());
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
        MW.searchMW(URLTextField.getText(), SearchTextField.getText());
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    /**
     * @param listFiles
     */
    public static void startAgain(File[] listFiles) {
        DisplayPanel.removeAll();
        DisplayPanel.revalidate();
        DisplayPanel.repaint();
        URLTextField.setText(Middleware.getPath());
        for (File file : listFiles) {
            System.out.println("File:" + file.getPath());
            if (!(file.isHidden())) {
                makeJButton(file, true);
            }
        }
    }

    public static void start(File[] listFiles) {
        DisplayPanel.removeAll();
        DisplayPanel.revalidate();
        DisplayPanel.repaint();
        URLTextField.setText("This PC");
        for (File file : listFiles) {
            System.out.println("File:" + file.getPath());
            makeJButton(file, false);
        }
    }

    public static void makeJButton(File file, boolean isSearch) {
        JButton btn = Middleware.makeButton(file, isSearch);
        DisplayPanel.add(btn);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackJButton;
    private javax.swing.JScrollPane BackPanel;
    private javax.swing.JButton BackjButton;
    private javax.swing.JButton CopyJButton;
    private javax.swing.JButton DeleteJButton;
    private javax.swing.JButton DesktopJButton;
    private static javax.swing.JPanel DisplayPanel;
    private javax.swing.JButton DocumentJButton;
    private javax.swing.JButton DownloadJButton;
    private javax.swing.JButton MovejButton;
    private javax.swing.JButton MusicJButton;
    private javax.swing.JButton NewJButton;
    private javax.swing.JButton PasteJButton;
    private javax.swing.JButton PicturesJButton;
    private javax.swing.JButton RenameJButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton ThisPCJButton;
    private static javax.swing.JTextField URLTextField;
    private javax.swing.JButton VideosJButton;
    private javax.swing.JButton ViewJButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
